#!/usr/bin/env bash

export ROOT="${TELEPRESENCE_ROOT:-}"

mkdir -p /root/.ssh
SSH_PRIVATE_KEY=$(echo -n $HOME_ASSISTANT_SSH_KEY_PRIVATE | sed -e 's/\\n/\n/g')
echo -e "${SSH_PRIVATE_KEY}" >/root/.ssh/id_rsa
echo -e "${HOME_ASSISTANT_SSH_KEY_PUBLIC}" >/root/.ssh/id_rsa.pub
chmod 0600 /root/.ssh/*

echo "
APPDAEMON_PASSWORD: \"${HOME_ASSISTANT_APPDAEMON_PASSWORD}\"
APPDAEMON_URL: \"${HOME_ASSISTANT_APPDAEMON_URL}\"
DOUBLE_TAKE_TOKEN: \"${HOME_ASSISTANT_DOUBLE_TAKE_TOKEN}\"
ELEVATION: \"${HOME_ASSISTANT_ELEVATION}\"
GAMING_ROOM_GAMING_PC_IP: \"${HOME_ASSISTANT_GAME_ROOM_GAMING_PC_IP}\"
GAMING_ROOM_GAMING_PC_MAC: \"${HOME_ASSISTANT_GAME_ROOM_GAMING_PC_MAC}\"
GAMING_ROOM_MACHINE_USERNAME: \"${HOME_ASSISTANT_GAME_ROOM_GAMING_PC_MACHINE_USERNAME}\"
GAMING_ROOM_NVIDIA_SHIELD_IP: \"${HOME_ASSISTANT_GAME_ROOM_NVIDIA_SHIELD_IP}\"
GAMING_ROOM_PLAYSTATION_5_IP: \"${HOME_ASSISTANT_GAME_ROOM_PLAYSTATION_5_IP}\"
GAMING_ROOM_TV_IP: \"${HOME_ASSISTANT_GAME_ROOM_TV_IP}\"
GAMING_ROOM_TV_MAC: \"${HOME_ASSISTANT_GAME_ROOM_TV_MAC}\"
GITHUB_RUNNER_AUTH_HEADER: \"token ${HOME_ASSISTANT_GITHUB_TOKEN}\"
GOOGLE_CALENDAR_CLIENT_ID: \"${HOME_ASSISTANT_GOOGLE_CALENDAR_CLIENT_ID}\"
GOOGLE_CALENDAR_CLIENT_SECRET: \"${HOME_ASSISTANT_GOOGLE_CALENDAR_CLIENT_SECRET}\"
HA_TOKEN: \"${HOME_ASSISTANT_TOKEN}\"
HA_URL: \"${HOME_ASSISTANT_SERVER}\"
HOME_AUTOMATION_PRIVATE_SSH_KEY: \"${SSH_PRIVATE_KEY}\"
HOME_AUTOMATION_PUBLIC_SSH_KEY: \"${HOME_ASSISTANT_SSH_KEY_PUBLIC}\"
INFLUXDB_TOKEN: \"${HOME_ASSISTANT_INFLUXDB_TOKEN}\"
JIRA_AUTHORIZATION_HEADER: \"${HOME_ASSISTANT_JIRA_AUTHORIZATION_HEADER}\"
LATITUDE: \"${HOME_ASSISTANT_LATITUDE}\"
LONGITUDE: \"${HOME_ASSISTANT_LONGITUDE}\"
POSTGRES_DB: \"${HOME_ASSISTANT_POSTGRES_DB}\"
POSTGRES_PASSWORD: \"${HOME_ASSISTANT_POSTGRES_PASSWORD}\"
POSTGRES_USER: \"${HOME_ASSISTANT_POSTGRES_USERNAME}\"
ROUTER_IP: \"${UNIFI_IP}\"
SPOTCAST_DC: \"${HOME_ASSISTANT_SPOTCAST_DC}\"
SPOTCAST_DC_2: \"${HOME_ASSISTANT_SPOTCAST_DC_2}\"
SPOTCAST_KEY: \"${HOME_ASSISTANT_SPOTCAST_KEY}\"
SPOTCAST_KEY_2: \"${HOME_ASSISTANT_SPOTCAST_KEY_2}\"
TIME_ZONE: \"${HOME_ASSISTANT_TIME_ZONE}\"
UNIFI_PASSWORD: \"${UNIFI_PASSWORD}\"
UNIFI_USERNAME: \"${UNIFI_USERNAME}\"
UNIT_SYSTEM: \"${HOME_ASSISTANT_UNIT_SYSTEM}\"
MQTT_USERNAME: \"${MQTT_USERNAME}\"
MQTT_PASSWORD: \"${MQTT_PASSWORD}\"
TURN_OFF_GAMING_ROOM_GAMING_PC_COMMAND: \"ssh -n -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa ${HOME_ASSISTANT_GAME_ROOM_GAMING_PC_MACHINE_USERNAME}@${HOME_ASSISTANT_GAME_ROOM_GAMING_PC_IP} \\\"C:\\\\Windows\\\\System32\\\\rundll32.exe powrprof.dll,SetSuspendState Standby\\\"\"
DB_URL: \"postgresql://${HOME_ASSISTANT_POSTGRES_USERNAME}:${HOME_ASSISTANT_POSTGRES_PASSWORD}@home-assistant-postgres:5432/${HOME_ASSISTANT_POSTGRES_DB}\"
SPOTIFY_CLIENT_ID: \"${HOME_ASSISTANT_SPOTIFY_CLIENT_ID}\"
SPOTIFY_CLIENT_SECRET: \"${HOME_ASSISTANT_SPOTIFY_CLIENT_SECRET}\"
" >/config/secrets.yaml

if [ ! -z "$TELEPRESENCE_ROOT" ]; then
    export SHELL=/bin/bash
    if [ -d "$TELEPRESENCE_ROOT" ]; then
        echo "Copying volume mount config."
        rsync -a --exclude=*.log "$TELEPRESENCE_ROOT/" /config
    fi
    /sync.sh /home-assistant-src
    chokidar "/home-assistant-src/**/*.yaml" "/home-assistant-src/custom_components/**/*.*" -c "bash -c '/sync.sh /home-assistant-src'" &
    chokidar "/config/**/*.yaml" --debounce 20000 -c "bash -c '/reload.sh || true'" &
fi

echo 'Starting HA'
hass --config /config
