#!/usr/bin/env bash

curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/automation/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/group/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/input_boolean/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/input_button/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/input_datetime/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/input_number/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/input_select/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/input_text/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/people/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/binary_sensor/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/scene/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/script/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/template/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/media_player/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/zone/reload"
curl -X POST -H "Authorization: Bearer $HASS_TOKEN" -H "Content-Type: application/json" "$HASS_SERVER/api/services/homeassistant/reload_core_config"
